_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
comment:
    value: ""
config:
    value: aapm_img.yml
data:
    value: Namespace(dataset='AAPM', image_size=256, channels=10, logit_transform=False, random_flip=False)
device:
    value: cuda
doc:
    value: AapmCT_10C
image_folder:
    value: output
log:
    value: run/logs/AapmCT_10C
model:
    value: Namespace(sigma_begin=1, sigma_end=0.01, num_classes=12, batch_norm=False, ngf=64)
optim:
    value: Namespace(weight_decay=0.0, optimizer='Adam', lr=0.001, beta1=0.9, amsgrad=False)
resume_training:
    value: false
run:
    value: run
runner:
    value: AapmRunnerdata_10C
seed:
    value: 1234
test:
    value: false
training:
    value: Namespace(batch_size=1, n_epochs=500000, n_iters=100001, ngpu='0,1', snapshot_freq=1000, algo='dsm', anneal_power=2.0)
verbose:
    value: info
